notifications:
  email:
    on_success: never
    on_failure: never

language: php
php:
  - 7.3
  - 7.2
  - 5.6

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar  

script:
  - phpunit --bootstrap test/config.php test

script:
  - phpunit --bootstrap test/config.php --coverage-clover coverage.clover test

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
